#Site settings
title: "Bootcamp Chronicles"
email: "thegopherguy@yahoo.com"
description: > # this means to ignore newlines until "baseurl:"
  This is the quick but important journey through Rockit Bootcamp. As I learn new things
  in this field I will update this blog to show everyone what a coding bootcamp offers.
baseurl: "/Levi_Donaldson/" # the subpath of your site, e.g. /blog/
url: "http://lcdonaldson.github.io/Levi_Donaldson/" # the base hostname & protocol for your site
twitter_username: "@levi_donaldson"
github_username:  lcdonaldson

#Build settings
markdown: kramdown
